name: BetterTeleport
version: 0.01
author: Andre LaFleur
main: usa.alafleur.betterteleport.BetterTeleport
commands:
  loc:
    description: Add, query, and remove stored locations
    usage: /loc <add{x y z}> <alias> <"description of location"> | <list> | <remove> <alias>
  tele:
    description: Teleport to a given location
    usage: /tele <username|x y z|alias>